In [9]:
import numpy as np
import pandas as pd
import matplotlib as plt

In [32]:
# Basic method of Array
# a = np.array([1,2,3,4,5,6,7,8,9])
# indexing 
# a[0]

# to check the shape of array 
# a.shape

# a.dtype
# a

In [65]:
# Multidimensional
a = np.array([[1,2,3],[5,6,7],[9,10,11]])
b = np.array([[1,2,3],[5,6,7],[9,10,11]])
# a.shape
# a.dtype
# a.ndim
# a.size
# a.sum()
# a.sum(axis=0)
# a.sum(axis=1)
# a.mean()
# a.mean(axis=0)
# a.mean(axis=1)
# a.std()
# a.std(axis=0)
# a.std(axis=1)
# a.var()

# linear Algebra
# a.dot(b) #dot Product
# a@b      #cross product

In [99]:
a = np.array([[1,3,2],[5,6,7],[9,10,11]],dtype=np.int64)
b = np.array([[1, 2, 12],
       [3, 4,13],
       [5, 6,14]])
# np.sort(a)
# array([1, 2, 3, 4, 5, 6, 7, 8])
# for i in a:
#     print(a)
# a.dtype
# a
con = np.concatenate((a,b))
# con.ndim
# con.size
# con.shape
# con.reshape(3,3)

ValueError: cannot reshape array of size 18 into shape (3,3)

In [74]:
# np.zeros(3)
# np.ones(2)
# np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [4]:
data = pd.read_csv("anual.csv")
data

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2020,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,"733,258",ANZSIC06 divisions A-S (excluding classes K633...
1,2020,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,"660,630",ANZSIC06 divisions A-S (excluding classes K633...
2,2020,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,"54,342",ANZSIC06 divisions A-S (excluding classes K633...
3,2020,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,"18,285",ANZSIC06 divisions A-S (excluding classes K633...
4,2020,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,"654,872",ANZSIC06 divisions A-S (excluding classes K633...
...,...,...,...,...,...,...,...,...,...,...
37075,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
37076,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
37077,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
37078,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
37079,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [7]:
data.shape

(37080, 10)

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37080 entries, 0 to 37079
Data columns (total 10 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Year                         37080 non-null  int64
 1   Industry_aggregation_NZSIOC  37080 non-null  object
 2   Industry_code_NZSIOC         37080 non-null  object
 3   Industry_name_NZSIOC         37080 non-null  object
 4   Units                        37080 non-null  object
 5   Variable_code                37080 non-null  object
 6   Variable_name                37080 non-null  object
 7   Variable_category            37080 non-null  object
 8   Value                        37080 non-null  object
 9   Industry_code_ANZSIC06       37080 non-null  object
dtypes: int64(1), object(9)
memory usage: 2.8+ MB